export const initialState = {
  cabinetId: "",
  cabinetNumber: "",
  energyCompany: "",
  connectionPower: "",
  numberOfPhases: 0,
  consumerGroup: 0,
  agreedPowerOne: 0,
  agreedPowerTwo: 0,
  agreedPowerThree: 0,
  agreedPowerFour: 0,
  agreedPowerFive: 0,
  priceBlockOne: 0,
  priceBlockTwo: 0,
  priceBlockThree: 0,
  priceBlockFour: 0,
  priceBlockFive: 0,
  penaltiesBlockOne: 0,
  penaltiesBlockTwo: 0,
  penaltiesBlockThree: 0,
  penaltiesBlockFour: 0,
  penaltiesBlockFive: 0,
  lowPrice: 0,
  highPrice: 0,
};
